config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'trip#index', as: :top
  resources :trip, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :task, only: [:create, :update, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/trip_controller.rb
class TripController < ApplicationController
  def index
    if params[:show_all] == '1'
      @trips = Trip.all
    else
      @trips = Trip.where(has_traveled: false)
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    
    if @trip.save
      redirect_to top_path, notice: '旅行を新規に作成しました。'
    else
      puts "-----"
      puts "処理失敗"
      puts "-----"
    end
  end

  def show
    @trip = Trip.find(params[:id])
  end
  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)

    redirect_to trip_path, notice: '旅行情報を編集しました。'
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    redirect_to top_path, notice: '旅行を新規に作成しました。'
  end

  private
  def trip_params
    params.require(:trip).permit(:title, :detail, :start_date, :end_date, :image, :has_traveled)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/trip_helper.rb
module TripHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trip/edit.html.erb
<h1>旅行編集画面</h1>

<%= form_with(model: @trip, url: trip_index_path, method: :post, local: true) do |form| %>
  <%= form.text_field :title, value: @trip.title %>
  <%= form.text_area :detail, value: @trip.detail %>
  <%= form.date_select :start_date, value: @trip.start_date %>
  <%= form.date_select :end_date, value: @trip.end_date %>
  <%= form.text_field :image, value: @trip.image %>
  <%= form.submit "送信" %>
<% end %>

<%= form_with(model: @trip, url: trip_path(id: @trip.id), method: :delete, local: true) do |form| %>
  <%= form.submit "削除" %>
<% end %>

<%= link_to '旅行一覧に戻る', top_path %>

app/views/trip/index.html.erb
<h1>Trip#index</h1>
<p>Find me in app/views/trip/index.html.erb</p>

<%= form_with url: top_path, method: :get, local: true do %>
  <div>
    <%= check_box_tag :show_all, '1', params[:show_all] == '1' %>
    <%= label_tag :show_all, 'すべての旅行を表示' %>
    <%= submit_tag '表示' %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>旅行名</th>
      <th>開始日</th>
      <th>終了日</th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.id %></td>
        <td><%= trip.title %></td>
        <td><%= trip.start_date %></td>
        <td><%= trip.end_date %></td>
        <td><%= link_to 'check todo', trip_path(id: trip.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '旅行を新規作成する', new_trip_path %>

app/views/trip/new.html.erb
<h1>Trip#new</h1>
<p>Find me in app/views/trip/new.html.erb</p>

<%= form_with(model: @trip, url: trip_index_path, method: :post, local: true) do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :detail %>
  <%= form.date_select :start_date %>
  <%= form.date_select :end_date %>
  <%= form.text_field :image %>
  <%= form.submit "送信" %>
<% end %>

<%= link_to '旅行一覧に戻る', top_path %>

app/views/trip/show.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>旅行名</th>
      <th>開始日</th>
      <th>終了日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td><%= @trip.id %></td>
    <td><%= @trip.title %></td>
    <td><%= @trip.start_date %></td>
    <td><%= @trip.end_date %></td>
    </tr>
  </tbody>
</table>

<%= link_to '旅行情報を編集', edit_trip_path(id: @trip.id) %>
<%= link_to '旅行一覧に戻る', top_path %>